accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('register/', register, name='register'),
]

post/urls.py
from django.urls import path

from post.models import Post
from . import views
from django.views.generic.detail import DetailView

app_name = 'post'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('upload', views.UploadView.as_view(), name='post_create'),
    path('single/<int:pk>', DetailView.as_view(model=Post, template_name='post/detail.html'), name='post_detail'),
    path('update<int:pk>', views.PostUpdateView.as_view(), name='post_update'),
    path('delete/<int:pk>', views.PostDeleteView.as_view(), name='post_delete'),

]

accounts/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='photo_posts')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True, default='photos/no_image.png')

    class Meta:
        ordering = ['-updated']

    def __str__(self):
        return self.author.username + " " + self.created.strftime("%Y-%m-%d %H:%M:%S")

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('post:post_detail', args=[str(self.id)])

accounts/forms.py
from django.contrib.auth.models import User
from django import forms

class ResisterForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match')
        return cd['password2']

accounts/views.py
from django.shortcuts import render
from .forms import *

# Create your views here.

def register(request):
    if request.method == 'POST':
        user_form = ResisterForm(request.POST)

        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'registration/register_done.html', {'new_user':new_user})
    else:
        user_form = ResisterForm()

    return render(request, 'registration/register.html', {'form':user_form})

post/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from .models import Post
from django.views.generic.edit import UpdateView, DeleteView, CreateView



# Create your views here.
@login_required
def post_list(request):
    posts = Post.objects.all()
    return render(request, 'post/list.html', {'posts':posts})

class UploadView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['photo', 'text']
    template_name = 'post/upload.html'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else :
            return self.render_to_response({'form':form})


class PostUpdateView(UpdateView):
    model = Post
    fields = ['photo', 'text']
    template_name = 'post/upload.html'

class PostDeleteView(DeleteView):
    model = Post
    success_url = '/'

post/templates/post/detail.html
{% extends 'base.html' %}

{% block title %}
    {{object.text|truncatechars:10}}
{% endblock %}

{% block content %}
    <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default">
                <p><img src="{{object.photo.url}}" style="width:100%;"></p>
                <button type="button" class="btn btn-outline-primary btn-sm">
                    {{object.author.username}}</button>
                <p>{{object.text|linebreaksbr}}</p>

                <a href="{% url 'post:post_delete' pk=object.id %}" class="btn btn-outline-danger btn-sm float-right">
                    Delete</a>
                <a href="{% url 'post:post_update' pk=object.id %}" class="btn btn-outline-success btn-sm float-right">
                    Update</a>
            </div>
            <div class="col-md-2"></div>
    </div>

    <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default">
                {% load disqus_tags %}
                {% disqus_show_comments %}
            </div>
            <div class="col-md-2"></div>
    </div>
{% endblock %}

post/templates/post/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
Index
</body>
</html>

post/templates/post/list.html
{% extends 'base.html' %}

{% block title %}Photo List{% endblock %}

{% block content %}
    {% for post in posts %}
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default">
                <p><img src="{{post.photo.url}}" style="width:100%;"></p>
                <button type="button" class="btw btn-xs btn-info">
                    {{post.author.username}}</button>
                <p>{{post.text|linebreaksbr}}</p>
                <p class="text-right">
                    <a href="{% url 'post:post_detail' pk=post.id %}" class="btn btn-xs btn-success">댓글달기</a>
                </p>
            </div>
            <div class="col-md-2"></div>
        </div>
    {% endfor %}
{% endblock %}

post/templates/post/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
Confirm Delete
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <form action="" method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input class="btn btn-danger" type="submit" value="Delete">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>

{% endblock %}

post/templates/post/upload.html
{% extends 'base.html' %}

{% block title %}
Photo Upload
{% endblock %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <link href="https://getbootstrap.com/docs/4.0/examples/narrow-jumbotron/narrow-jumbotron.css" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
    <title>Tstagram {% block title %}{% endblock %}</title>
    {% load static %}
    <link href='{% static "css/style.css" %}' rel="stylesheet">
</head>
<body>
<div class="container">
    <header class="header clearfix">
        <nav>
            <ul class="nav float-right">
                <li class="nav-item"><a href="/" class="active nav-link ">Home</a></li>
                {% if user.is_active %}
                <li class="nav-item"><a href="#" class="nav-link">Welcome, {{user.get_username}}</a></li>
                <li class="nav-item"><a href="{% url 'post:post_create' %}" class="nav-link">Upload</a></li>
                <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link">Logout</a></li>
                {% else %}
                <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link">Login</a></li>
                <li class="nav-item"><a href="{% url 'accounts:register' %}" class="nav-link">Register</a></li>
                {% endif %}
            </ul>
        </nav>
        <h3 class="text-muted">Tstagram</h3>
    </header>
    {% block content %}
    {% endblock %}

    <footer class="footer">
        <p>2018 KyutaeLee</p>
    </footer>
</div>


</body>
</html>